services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    depends_on:
      - zero
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0

  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    depends_on:
      - alpha
    command: dgraph-ratel

volumes:
  dgraph-data:
